### PR TITLE
Simplify keyboard shortcuts to avoid combo key presses

### PR DESCRIPTION
**Pull request by danielhjames**
This avoids having to make a three-finger combo to rescan the crate, or a two-finger combo to toggle sort mode. It's simply left control key for rescan and left alt to toggle sort mode, which sit nicely with the existing tab key for toggling 'All records'.

### CODE REVIEW

**Comment by lpil** [comment]
I would prefer not to use alt. As applications tend not to just alt I've been able to use alt for window manager hotkeys without it conflicting with other applications.

**Comment by danielhjames** [comment]
Hi Louis, since xwax search does not accept upper case input, the left shift key works just as well as left alt for toggling the sort order. I've updated the pull request.

**Comment by obbardc** [comment]
Hi, I have been polluting the main branch with some other additions which are of no use to this pull request.

Please do _not_ merge my changes noted above!

Cheers

**Comment by obbardc** [comment]
Please close this in favour of #2

**Pull request closed without merging**
